[Add オプション課題]
ShotaroHirose59/rspec_app_exam pull request #1
Opened 2020-01-28 06:43 UTC by ShotaroHirose59

実装途中となっている spec/system/task_spec.rb を修正してください。

各テストケースに修正内容をコメントしています。

・FIXME --> テストが失敗するので、成功するよう修正をお願いします。
・TODO --> テストは成功しますが、記載事項に沿ってリファクタリングしてください。

<img width="829" alt="スクリーンショット 2020-01-28 15 20 45" src="https://user-images.githubusercontent.com/55835461/73241291-f3643100-41e4-11ea-8d58-a79fe16792ef.png">

2020-01-28 06:46 UTC, yuji91 commented on spec/factories/tasks.rb
> +    end
`task :status`というtraitだと、それがどういう内容のテストデータか読み取れないです。

trait名からテストデータの内容や役割が読み取れるような名前をつけましょう。

2020-01-28 06:47 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).to have_content(Time.current.strftime('%-m/%d'))
`find('.task_list')`を変更した理由はありますか？

また`strftime`ではなく、View側の実装を参考にした修正にしてください。

2020-01-28 06:48 UTC, yuji91 requested changes
コメントしました！

2020-01-28 06:52 UTC, ShotaroHirose59 commented on spec/factories/tasks.rb
> +    end
8a80796 で修正しました！

2020-01-28 09:10 UTC, ShotaroHirose59 commented on spec/system/task_spec.rb
> +        expect(page).to have_content(Time.current.strftime('%-m/%d'))
苦戦してる時に変えてしまっていました
30be8a0 で修正しました！

2020-01-28 09:19 UTC, yuji91 requested changes
コメントしました！

自分の実装したコードを前提知識のない他の開発者が読んだときに理解しやすい内容になるように意識して実装しましょう！

2020-01-28 09:21 UTC, yuji91 commented on spec/factories/tasks.rb
> +      status { 'done' }
`status_is_done`だとstatusが増えるごとに同じ名前でtraitを用意することになるかと思います。
また、1つのカラム内容しか変えないのであれば、
`let(:task_is_done) { create  :task, status: :done }`と定義時に宣言すれば済みます。

今回は`completion_date`という`完了日付`もカラムにあるので、doneになった場合はこのカラムも値があることが望ましいです。

2020-01-28 09:21 UTC, yuji91 commented on spec/rails_helper.rb
> +end
このメソッドをここで定義してしまうと、Viewで使っているhelperの表示形式の仕様が変わると結局このテストも落ちてしまいます。

実装側で利用しているhelperをincludeしてそのまま呼び出す形にしましょう！

2020-01-28 09:22 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = FactoryBot.create(:task, :status_is_done, :completion_date, project_id: project.id)
`FactoryBot`は省略して記載できるようにしてください。

2020-01-28 09:54 UTC, ShotaroHirose59 commented on spec/rails_helper.rb
> +end
c95d373 で修正しました！

2020-01-28 10:18 UTC, ShotaroHirose59 commented on spec/system/task_spec.rb
> +        task = FactoryBot.create(:task, :status_is_done, :completion_date, project_id: project.id)
3f81de3 で修正しました！

2020-01-28 10:18 UTC, ShotaroHirose59 commented on spec/factories/tasks.rb
> +      status { 'done' }
25c27db で修正しました！

2020-01-28 10:28 UTC, yuji91 commented on spec/factories/tasks.rb
> +    trait :completed_state do
この`trait`で設定される属性はstatusだけではないですよね？
「どのような内容の`task`のテストデータを作成したいのか」という観点で変更してみてください。

また、カラム名がstatusなのにtrait名がstateと統一されていない点も紛らわしくなっていますね。

2020-01-28 10:28 UTC, yuji91 requested changes
コメントしました！

2020-01-28 11:26 UTC, ShotaroHirose59 commented on spec/factories/tasks.rb
> +    trait :completed_state do
ccbb3af で修正し、statusを2にしてしまっていたことに気付いたので
d7d3ed1 でstatusを:doneに修正しました！

2020-01-28 11:35 UTC, yuji91 commented
state名がdoneなのでcompletedよりはステータスの名前と近いdoneの方が良いかもしれません。
completedというステータスがあれば現状の方が良いです。

また、シングルクォートで囲んでいる昨日の日付が登録されるかを併せて確認お願いします。

2020-01-28 11:49 UTC, ShotaroHirose59 commented
> state名がdoneなのでcompletedよりはステータスの名前と近いdoneの方が良いかもしれません。
> completedというステータスがあれば現状の方が良いです。
> 
> また、シングルクォートで囲んでいる昨日の日付が登録されるかを併せて確認お願いします。

2020-01-28 12:14 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :done, project_id: project.id)
associationが設定されているのでprojectを指定する必要はなくなったと思います！

2020-01-28 12:15 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, project_id: project.id)
`let`使っているので再度Factory呼び出す必要ないと思います！

2020-01-28 12:17 UTC, yuji91 commented on spec/rails_helper.rb
> +  config.include ApplicationHelper
修正不要でこのままで大丈夫ですが、
ここで指定すると全体のSpecファイルに適用され、ファイルで個別にincludeするとそのファイルのみに適用されるので使い分け出来ることは知っておいてください！

2020-01-28 12:17 UTC, yuji91 requested changes
コメントしました！

2020-01-29 10:44 UTC, ShotaroHirose59 commented on spec/system/task_spec.rb
> +        task = create(:task, :done, project_id: project.id)
0005897 で修正しました！

2020-01-29 10:44 UTC, ShotaroHirose59 commented on spec/system/task_spec.rb
> +        task = create(:task, project_id: project.id)
f1c03d7 で修正しました！

2020-01-29 10:44 UTC, ShotaroHirose59 commented on spec/rails_helper.rb
> +  config.include ApplicationHelper
個別にincludeして適応されることを確認しました！

2020-01-30 04:51 UTC, yuji91 commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(windows.last)
`switch_to_window(windows.last)`と1行で記載することもできるはずです！
本質的な部分ではないので確認だけしておいてください。

2020-01-30 04:54 UTC, yuji91 commented on spec/support/driver_setting.rb
> +    #driven_by(:selenium_chrome_headless)
修正不要ですが、`selenium_chrome_headless`から`selenium_chrome`に変えるとブラウザが起動されますが、Rspec実行時の時間的コストがかかるため、リモートブランチにはコミットせず、ローカルで変更して元に戻すというやり方の方が良いと思います！

2020-01-30 04:57 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
`trait`がdoneのタスクを作成しているので、変数名も`task_done`などにした方がいいかと思います。

letでtraitを使ったtaskを定義すれば、下記の1行でcreateしてそのオブジェクトのIDを指定することが可能です。
`visit edit_project_task_path(project, task_done)`

2020-01-30 04:59 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('table')).not_to have_content task.title
tableでも良いですが、cssを適用させているidがあります。
（Viewを見ると、色が変わっている部分があるかと思います。）

2020-01-30 04:59 UTC, yuji91 requested changes
コメントしました！

2020-01-30 05:32 UTC, ShotaroHirose59 commented on spec/system/task_spec.rb
> +        expect(find('table')).not_to have_content task.title
7974e13 で修正しました！

2020-01-30 05:32 UTC, ShotaroHirose59 commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
254aafd で修正しました！

2020-01-30 05:32 UTC, ShotaroHirose59 commented on spec/support/driver_setting.rb
> +    #driven_by(:selenium_chrome_headless)
わかりました！

2020-01-30 05:32 UTC, ShotaroHirose59 commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(windows.last)
switch_to_window(windows.last) でテストが通ることを確認しました！

2020-01-30 10:23 UTC, yuji91 commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(windows.last)
このコメント欄も`で囲むとコードが見やすくなるので知っておいてください。

2020-01-30 10:23 UTC, yuji91 approved these changes
LGTMです！

2020-01-31 03:19 UTC, merged